[project]
name = "nbim-case"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.27",
    "litellm>=1.76.3",
    "pandas>=2.3.2",
    "smolagents[litellm]>=1.21.3",
]
